# Generated by Django 5.2.4 on 2025-09-30 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_room_complaint_notice_roomapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_reason', models.TextField(blank=True)),
                ('allocation_notes', models.TextField(blank=True, help_text='Notes about this allocation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_allocations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel_management.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='hostel_management.studentprofile')),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
                'ordering': ['-allocated_date'],
            },
        ),
    ]
